switcheroo/urls.py
from django.contrib import admin
from . import views
from django.conf.urls import url
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
        path('accounts/',include('django.contrib.auth.urls')),
        path('main/', include('project_specific.urls')),
        path('', views.main_page_view, name='home'),
        path('users/', include('user.urls')),
        path('users/', include('django.contrib.auth.urls')),
        url(r'^login/$', views.login_view, name='login'),
        ]

from switcheroo import views
handler500 = views.handler500

user/urls.py
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 12 22:07:12 2019

@author: Oliver
"""

from django.urls import path
from .views import SignUpView

urlpatterns = [
               path('signup/', SignUpView.as_view(), name='signup'),
               ]

user/forms.py
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 12 20:47:48 2019

@author: Oliver
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Group


class CustomUserCreationForm(UserCreationForm):
    employee_id = forms.IntegerField(min_value=0)
    is_manager = forms.BooleanField(required=False)

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email', 'first_name', 'last_name')


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm):
        model = CustomUser
        fields = ('email', 'first_name', 'last_name')

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>

<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
 
  {% load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  {% block static %}{% endblock %}
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}

    {% block javascript %}{% endblock %}
  </main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block static %}
{% load staticfiles %}
<link rel='stylesheet' type='text/css' href="{% static 'css/home.css'%}">
{% endblock %}

{% block title %}Home{% endblock %}

{% block content %}

<nav class="nvbar navbar-inverse navbar-default">
  <div class='container-fluid'>
    <div class='navbar-header'>
      <a class='navbar-brand' href="">Switcheroo</a>
        </div>
        
    <ul class="nav navbar-nav navbar-right">
        <li><a href="/users/login/"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
</nav>	

<div class='container-fluid'>
  <div class='row'>
    <div id='titleSection' class='hero-text'>
      <h1>Switcheroo</h1>
      <h4>Scheduling made easy</h4>
    </div>
  </div>

  <div class='row'>
      <div id='introduction' class='col-xs-10 col-sm-10 col-md-10 col-lg-10 
      col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1'>
        <h2>What is Switcheroo?</h2>
        <p>Switcheroo is a free web app built on Django that solves the tedious task of arranging shifts for employee and shift switching. 
          It is useful for organization with a lot of employees that have the same position.
        </p>

        <h4>Problems addressed</h4>
        <h5 style='font-weight: bold;'>Scheduling</h5>
        <p>Some managers sit down at their desk and spend hours arranging shifts for employees on Excel. 
          This is horribly inefficient. With Switcheroo, scheduling can be done on a pattern basis. Suppose
          you have a 2 morning shifts, 2 night shifts, 4 rest days schedule for your employees, you can 
          create that scheduling pattern with Switcheroo and assign to users repeatedly. Furthermore, you can assign
          shifts automatically across multiple users at once.
        </p>

        <h5 style='font-weight: bold;'>Shift Switching</h5>
        <p>When the employee pool grows, it becomes harder to keep track who is open to accept shifts. With 
          Switcheroo, you no longer have to text every co-workers asking if they are free. The algorithm takes 
          care of finding the right match for you. All you have to do is select who you want switch the shift with. 
          The finalizing of shift switch is automatically sent to manager for approval.
        </p>
      </div>
  </div>
    

  <div class='row'>
      <div id='managerFeatures' class='col-xs-12 col-sm-8 col-md-8 col-lg-8 
      col-md-offset-1 col-lg-offset-1'>
        <h3>Features for managers</h3>
          <ul>Schedule assignment based on shifts patterns
            <li>Shifts are the unit block of schedules. Combine different shifts to form a schedule pattern</li>
            <li>Schedule patterns are in blocks of days</li>
          </ul>

          <ul>Scheduling
            <li>Assignments are done with starting dates</li>
            <li>Scheduling can also be done automatic! The algorithm will sort out the optimal shift assignment
                based on the workers needed per day, employees' preferred work days, and seniority</li>
          </ul>

          <ul>View employee's schedule
            <li>Easily view each employee's schedule in calendar</li>
          </ul>

          <ul>Employee management
            <li>One manager is in charge of a group of employees. The shifts and schedule patterns created belong only to this group</li>
            <li>Each employee only belongs to one group</li>
            <li>A manager can be an employee as well. This means you can stack your groups and create a whole organization!</li>
          </ul>

          <ul>People
            <li>Each group can contain different types of employees with different units and positions</li>
            <li>Units and positions are internal to the group. For example, manager A's unit "logistics" is different from manager B's "logistics". Same for positions</li>
            <li>You can create as many different types of units and positions as requied. <b>Note:</b> shifts switches are only made within employees that belong to same group, unit, and position</li>
          </ul>
      </div>
      <div id='managerIllustrations' class='col-xs-12 col-sm-4 col-md-2 col-lg-2'>
        <img src="static/switcheroo-explanation.png" alt="switcheroo explanation" class='img-fluid'>
      </div>
  </div>

  <div class='row'>
    <div id='employeeFeatures' class='col-xs-12 col-sm-8 col-md-8 col-lg-8 
    col-md-offset-1 col-lg-offset-1'>
      <h3>Features for employees</h3>
      <ul>Shift switching
        <li>If you want to switch shift with someone on a particular day, all you have to do is choose a shift on the calendar, and click swap. The algorithm
          will find the a list of possible matches. Once you select a shift to swap with, the request will be sent to the receiver. 
          If receiver agrees, the request will be finalized for approval by manager. If manager agrees, the swap will be done automatically.
        </li>
        <li>You can switch a range of shifts all at once! No more texting other employees asking if they are free</li>
        <li>Options to accept more shifts</li>
        <li>View shift switch approval status</li>
      </ul>

      <ul>Vacation days
        <li>Directly request vacation dates. Vacation dates will be sent to manager for approval</li>
        <li>Once approved, the shift scheduling will not assign any shift on the vacation day</li>
        <li>You can request a range of vacation days for approval</li>
        <li>View vacation approval status</li>
      </ul>

    </div>

    <div id='employeeIllustrations' class='col-xs-12 col-sm-4 col-md-2 col-lg-2'>
      <img src="" alt="">
    </div>
  </div>

  <div class='row'>
    <div id='testing' class='col-xs-10 col-sm-10 col-md-10 col-lg-10 
    col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1'>
      <h2>Using the Demo Site</h2>
      <p><b>Note:</b> I did the development in Chrome and have not checked compatibilty with other browsers. For best experience, please use Chrome</p>
      <p>I have created some fake accounts for this demo site. To see how it works, click the top right log-in icon and enter the following information:</p>
      <ul>
        For Manager's View
        <li>Acc: demoManager@switcheroo.com</li>
        <li>Pass: MTest123</li>
      </ul>

      <ul>
        For Employee's view
        <ul>Employee 1
          <li>Acc: demoE1@switcheroo.com</li>
          <li>Pass: ETest123</li>
        </ul>

        <ul>Employee 2
          <li>Acc: demoE2@switcheroo.com</li>
          <li>Pass: ETest123</li>
        </ul>
      </ul>

      <p><b>Note:</b> Please don't enter any personal information as database is just for demonstration, isn't maintained, and is accessible by everyone.</p>
    </div>
  </div>
    
  <div class='row'>
    <div id='installation' class='col-xs-10 col-sm-10 col-md-10 col-lg-10 
    col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1'>
      <h2>How to install?</h2>
      <p>The source code is located on <a href="https://github.com/chestnutcone/switcheroo">GitHub</a>. There are still some features left to implement (ie security for example). 
      </p>

      <h2>Contact</h2>
      <p>If you want to get in touch with me, <a href="mailto:thisisoliverhuang@gmail.com">email me</a>. 
        For more of my work, visit my <a href="http://www.oliverhuang.ca/">personal website.</a></p>

    </div>
  </div>  
  



{% endblock %}

templates/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<div id='form-container'>
    <form method="POST" id='signUpForm' class='col-xs-10 col-sm-6 col-md-4 col-lg-4 
    col-xs-offset-1 col-sm-offset-3 col-md-offset-4 col-lg-offset-4'>
        {% csrf_token %}
        <h1>Sign Up</h1>
        <div class='form-group'>
          <label for='id_email'>Email</label>
          <input type="text" id='id_email' name="email" placeholder="Enter email" 
          required class='form-control' maxlength='254'>
        </div>

        <div class='form-group'>
            <label for="id_first_ame">First Name</label>
            <input type="text" id='id_first_ame' name='first_name' required 
            class='form-control' maxlength='30'>
        </div>

        <div class='form-group'>
          <label for="id_last_name">Last Name</label>
          <input type="text" id='id_last_name' name='last_name' required 
          class='form-control' maxlength="150">
        </div>
    
        <div class='form-group'>
          <label for='id_password1'>Password</label>
          <input type="password" id='id_password1' name="password1" placeholder="Enter password" required
          class='form-control'>
        </div>

        <div class='form-group'>
          <label for='id_password2'>Password</label>
          <input type="password" id='id_password2' name="password2" placeholder="Enter password" required
          class='form-control'>
        </div>
    
        <div class='form-group'>
          <label for="id_employee_id">Employee ID</label>
          <input type="number" id='id_employee_id' name='employee_id' min='0' required class='form-control'>
        </div>

        <div class="form-group">
          <label for="id_is_manager">Manager Status</label>
          <input type="checkbox" id='id_is_manager' name='is_manager' class='form-control'>
        </div>
        <button type="submit" class='btn btn-block'>Sign Up</button>
    </form>
  </div>
  
{% endblock %}